// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/detalle/:nombre": {
    params: {
      "nombre": string;
    };
  };
  "/arrepentimiento": {
    params: {};
  };
  "/reset_password": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/detalle/:nombre" | "/arrepentimiento" | "/reset_password" | "/products" | "/register" | "/login" | "/*";
  };
  "routes/[detalle].$[nombre]._index.jsx": {
    id: "routes/[detalle].$[nombre]._index";
    page: "/detalle/:nombre";
  };
  "routes/[arrepentimiento]._index.jsx": {
    id: "routes/[arrepentimiento]._index";
    page: "/arrepentimiento";
  };
  "routes/[reset_password]._index.jsx": {
    id: "routes/[reset_password]._index";
    page: "/reset_password";
  };
  "routes/[products]._index.jsx": {
    id: "routes/[products]._index";
    page: "/products";
  };
  "routes/[register]._index.jsx": {
    id: "routes/[register]._index";
    page: "/register";
  };
  "routes/[login]._index.jsx": {
    id: "routes/[login]._index";
    page: "/login";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};