// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/detalle/:nombre": {
    params: {
      "nombre": string;
    };
  };
  "/arrepentimiento": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/detalle/:nombre" | "/arrepentimiento" | "/products" | "/*";
  };
  "routes/[detalle].$[nombre]._index.jsx": {
    id: "routes/[detalle].$[nombre]._index";
    page: "/detalle/:nombre";
  };
  "routes/[arrepentimiento]._index.jsx": {
    id: "routes/[arrepentimiento]._index";
    page: "/arrepentimiento";
  };
  "routes/[products]._index.jsx": {
    id: "routes/[products]._index";
    page: "/products";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};